### ISSUE TITLE
Can not get static image from mounts

### ISSUE THREAD

**Issue by peanut996** [hugomods/images#16]
when enable image module, it can not work properly with `mounts` such config: 

```toml
[module]
[[module.imports]]
path = 'github.com/hugomods/images'
[[module.mounts]]
source = 'images'
target = 'static/images'
```

can not use `![](images/1.png)` in markdown to get the image which locates on `$root/images/1.png`
